import Button from "components/Button";
import { useSubmitCodeMutation } from "features/user/UserSlice";
import { useEffect, useState } from "react";
import { StyleSheet, Text, ToastAndroid } from "react-native";
import { View } from "react-native";
import { Tooltip } from "react-native-elements";
import AntDesign from "@expo/vector-icons/AntDesign";
import { TextInput } from "react-native-paper";

export default function CodeInput({ route, navigation }) {
  const [code, setCode] = useState("");
  const [submitCode] = useSubmitCodeMutation();

  useEffect(() => {
    const sumitCodeOnComplete = async () => {
      try {
        if (code.length === 4) {
          await submitCode({ generatedCode: code })
            .unwrap()
            .then((res) => {
              navigation.navigate("RegistrationForm", {
                floor: res.floor,
                room: res.room,
              });
            });
        }
      } catch (e) {
        console.error("Error submitting code", e);
        ToastAndroid.show(
          "An error occurred, please try again later",
          ToastAndroid.SHORT
        );
      }
    };
    sumitCodeOnComplete();
    navigation.navigate("RegistrationForm");
  }, [code]);

  return (
    <View
      style={{
        display: "flex",
        flexDirection: "column",
        justifyContent: "center",
        alignItems: "center",
        gap: 10,
        marginTop: "auto",
        marginBottom: "auto",
      }}
    >
      <View style={styles.codeArea}>
        <TextInput
          style={styles.codeInput}
          mode="flat"
         placeholder="Code"
          onChangeText={(text) => setCode(text.toUpperCase())}
          value={code}
          maxLength={4}
        />
        <Tooltip
          width={300}
          height={120}
          popover={
            <Text style={styles.tip}>
              Please ask one of your fellow residents to generate a code from
              the app. Code can be generated by going to the all residents tab
              in the home screen. The code is not case sensitive.
            </Text>
          }
        >
          <AntDesign name="questioncircleo" size={18} color="black" />
        </Tooltip>
      </View>
    </View>
  );
}

const styles = StyleSheet.create({
  tip: {
    fontSize: 16,
    textAlign: "center",
    color: "black",
  },
  codeArea: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 5,
  },
  codeInput: {
    width: 100,
    height: 40,
    borderColor: "black",
    borderWidth: 1,
    borderRadius: 5,
  },
});
